name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build contracts
      run: make all-via-docker

    - name: Run tests for secp256r1_blake160 rust
      run: cargo test
      working-directory: ./tests/secp256r1_blake160

    - name: Run tests for secp256r1_blake160 rust
      run: cargo test
      working-directory: ./tests/sudt_lua

    - name: Set up ckb-vm-runner
      run: |
        cargo install --example ckb-vm-runner --branch rvv --git https://github.com/nervosnetwork/ckb-vm.git --features asm ckb-vm

    - name: Run tests for secp256r1_blake160 c
      run: |
        ckb-vm-runner ./build/secp256r1_blake160_c
